import numpy as np
import matplotlib.pyplot as plt

#plt.subplot2grid(GridSpec, CurSpec, colspan=1,rowspan=1)

plt.subplot2grid((3,3),(0,0),colspan=3)
a = np.arange(0.0,5.0,0.02)
plt.plot(a,np.cos(2*np.pi*a),'r--')
plt.xlabel('横轴: 时间',fontproperties='Heiti TC',fontsize=10,color='green')
plt.ylabel('纵轴: 振幅',fontproperties='Heiti TC',fontsize=10)
plt.title(r'正弦波实例 $y=cos(2\pi x)$',fontproperties='Heiti TC',fontsize=16)
plt.annotate(r'$\mu=100$',xy=(2,1),xytext=(3,1.5),arrowprops=dict(facecolor='black',shrink=0.1,width=2))
plt.axis([-1,6,-2,2])
plt.grid(True)

plt.subplot2grid((3,3),(1,0),colspan=2)
a = np.arange(0.0,5.0,0.02)
plt.plot(a,np.cos(2*np.pi*a),'r--')
plt.xlabel('横轴: 时间',fontproperties='Heiti TC',fontsize=10,color='green')
plt.ylabel('纵轴: 振幅',fontproperties='Heiti TC',fontsize=10)
plt.title(r'正弦波实例 $y=cos(2\pi x)$',fontproperties='Heiti TC',fontsize=16)
plt.annotate(r'$\mu=100$',xy=(2,1),xytext=(3,1.5),arrowprops=dict(facecolor='black',shrink=0.1,width=2))
plt.axis([-1,6,-2,2])
plt.grid(True)

plt.subplot2grid((3,3),(1,2),colspan=2)
a = np.arange(0.0,5.0,0.02)
plt.plot(a,np.cos(2*np.pi*a),'r--')
plt.xlabel('横轴: 时间',fontproperties='Heiti TC',fontsize=10,color='green')
plt.ylabel('纵轴: 振幅',fontproperties='Heiti TC',fontsize=10)
plt.title(r'正弦波实例 $y=cos(2\pi x)$',fontproperties='Heiti TC',fontsize=16)
plt.annotate(r'$\mu=100$',xy=(2,1),xytext=(3,1.5),arrowprops=dict(facecolor='black',shrink=0.1,width=2))
plt.axis([-1,6,-2,2])
plt.grid(True)

plt.subplot2grid((3,3),(2,0))
a = np.arange(0.0,5.0,0.02)
plt.plot(a,np.cos(2*np.pi*a),'r--')
plt.xlabel('横轴: 时间',fontproperties='Heiti TC',fontsize=16,color='green')
plt.ylabel('纵轴: 振幅',fontproperties='Heiti TC',fontsize=16)
plt.title(r'正弦波实例 $y=cos(2\pi x)$',fontproperties='Heiti TC',fontsize=16)
plt.annotate(r'$\mu=100$',xy=(2,1),xytext=(3,1.5),arrowprops=dict(facecolor='black',shrink=0.1,width=2))
plt.axis([-1,6,-2,2])
plt.grid(True)

plt.subplot2grid((3,3),(2,1))
a = np.arange(0.0,5.0,0.02)
plt.plot(a,np.cos(2*np.pi*a),'r--')
plt.xlabel('横轴: 时间',fontproperties='Heiti TC',fontsize=10,color='green')
plt.ylabel('纵轴: 振幅',fontproperties='Heiti TC',fontsize=10)
plt.title(r'正弦波实例 $y=cos(2\pi x)$',fontproperties='Heiti TC',fontsize=16)
plt.annotate(r'$\mu=100$',xy=(2,1),xytext=(3,1.5),arrowprops=dict(facecolor='black',shrink=0.1,width=2))
plt.axis([-1,6,-2,2])
plt.grid(True)
plt.show()
